#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom &

$HOME/.config/startup.sh &

# Привязка рабочих столов к монитору(ам) -d
if [ -n "$DISPLAY_EXTERNAL" ]; then
    xrandr --output "$DISPLAY_EXTERNAL" --auto --left-of "$DISPLAY_INTERNAL" --output "$DISPLAY_EXTERNAL" --primary
    # Есть внешний монитор в переменной окружения
    bspc monitor "$DISPLAY_EXTERNAL" -d I II III IV V VI VII VIII
    bspc monitor "$DISPLAY_INTERNAL" -d IX X
else
    # Переменная не задана — считаем, что только встроенный экран
    bspc monitor "$DISPLAY_INTERNAL" -d I II III IV V VI VII VIII IX X
fi

# Рамки и отступы
bspc config border_width         2
bspc config window_gap          12

# Цвет рамки
bspc config normal_border_color "#0A1F32"
bspc config active_border_color "#2D384A"
bspc config focused_border_color "#344756"

# Цвет пространства при выборе положения нового окна
bspc config presel_feedback_color "#595B82"

# Фокус окна наведение курсора
bspc config focus_follows_pointer true
bspc config pointer_modifier	super

# Коэффициент разделение. Сколько процентов останется от родительского окна при открытии нового
bspc config split_ratio          0.52

# Отступы и рамки, когда открыто одно окно
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config paddingless_monocle	 true

# Схема открытия нового окна
#bspc config automatic_scheme	spiral

# Правила приложений
bspc rule -a Gimp state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a kate state=floating follow=on focus=on

bspc rule -a obsidian desktop='^6'
bspc rule -a nextcloud desktop='^6'

bspc rule -a Blueberry.py desktop='^8'
bspc rule -a nekobox desktop='^8'
bspc rule -a v2rayN desktop='^8'

bspc rule -a TelegramDesktop desktop='^9'
bspc rule -a yandex-music desktop='^9'

bspc rule -a qutebrowser desktop='^10'
bspc rule -a firefox desktop='^10'

$HOME/.config/polybar/launch.sh
if [ -n "$DISPLAY_EXTERNAL" ]; then
	$HOME/.config/polybar/launch_additional.sh
fi
